(* generated by Ott 0.34 from: ../ott/coq.ott *)

Require Import Arith.
Require Import Bool.
Require Import List.
Require Import Ott.ott_list_core.


From stdpp Require Import prelude strings gmap stringmap functions countable.

Definition cn : Set := string. (* component constant name *)
Definition Sn : Set := string. (* specification constant name *)
Definition q : Set := string. (* component variable *)
Definition V : Set := string. (* specification variable *)

Inductive Sc : Set :=  (* specification constant *)
 | Sc_const (Sn5:Sn) (* constant *)
 | Sc_compat : Sc (* compatibility *)
 | Sc_top : Sc (* top *).

Inductive c : Set :=  (* component term *)
 | c_const (cn5:cn) (* constant *)
 | c_comp (c5:c) (c':c) (* composition *)
 | c_var (q5:q) (* variable *).

Inductive S : Set :=  (* specification term *)
 | S_const (Sc5:Sc) (* constant *)
 | S_conj (S5:S) (S':S) (* conjunction *)
 | S_assume (S5:S) (S':S) (* assume-guarantee *)
 | S_par (S5:S) (S':S) (* parallel *)
 | S_var (V5:V) (* variable *).

Inductive P : Set :=  (* component specification predicate *)
 | P_implements (c5:c) (S5:S) (* implements *)
 | P_refines (S5:S) (S':S) (* refines *)
 | P_asserts (S5:S) (* assertional *)
 | P_forall_c (q5:q) (P5:P) (* for all components *)
 | P_exists_c (q5:q) (P5:P) (* exists component *)
 | P_forall_S (V5:V) (P5:P) (* for all specifications *)
 | P_exists_S (V5:V) (P5:P) (* exists specification *)
 | P_implies (P5:P) (P':P) (* implies *)
 | P_and (P5:P) (P':P) (* conjunction *)
 | P_or (P5:P) (P':P) (* disjunction *)
 | P_not (P5:P) (* negation *)
 | P_c_eq (c5:c) (c':c) (* component equals *)
 | P_S_eq (S5:S) (S':S) (* specification equals *).

Definition Q : Set := stringset.

Definition Sc2gt (Sc0:Sc) : gen_tree Sn :=
match Sc0 with
| Sc_const Sn0 => GenNode 0 [GenLeaf Sn0]
| Sc_compat => GenNode 1 []
| Sc_top => GenNode 2 []
end.

Definition gt2Sc (gt : gen_tree Sn) : option Sc :=
match gt with
| GenNode 0 [GenLeaf Sn0] => Some (Sc_const Sn0)
| GenNode 1 [] => Some Sc_compat
| GenNode 2 [] => Some Sc_top
| _ => None
end.

Fixpoint c2gt (c0:c) : gen_tree string :=
match c0 with
| c_const cn0 => GenNode 0 [GenLeaf cn0]
| c_comp c1 c2 => GenNode 1 [c2gt c1; c2gt c2]
| c_var q0 => GenNode 2 [GenLeaf q0]
end.

Fixpoint gt2c (gt : gen_tree string) : option c :=
match gt with
| GenNode 0 [GenLeaf cn0] => Some (c_const cn0)
| GenNode 1 [gt1; gt2] =>
  match gt2c gt1, gt2c gt2 with
  | Some c1, Some c2 => Some (c_comp c1 c2)
  | _,_ => None
  end
| GenNode 2 [GenLeaf q0] => Some (c_var q0)
| _ => None
end.

Fixpoint S2gt (S0:S) : gen_tree (Sc + string) :=
match S0 with
| S_const Sc0 => GenNode 0 [GenLeaf (inl Sc0)]
| S_conj S1 S2 => GenNode 1 [S2gt S1; S2gt S2]
| S_assume S1 S2 => GenNode 2 [S2gt S1; S2gt S2]
| S_par S1 S2 => GenNode 3 [S2gt S1; S2gt S2]
| S_var V0 => GenNode 4 [GenLeaf (inr V0)]
end.

Fixpoint gt2S (gt : gen_tree (Sc + V)) : option S :=
match gt with
| GenNode 0 [GenLeaf (inl Sc0)] => Some (S_const Sc0)
| GenNode 1 [gt1; gt2] =>
  match gt2S gt1, gt2S gt2 with
  | Some S1, Some S2 => Some (S_conj S1 S2)
  | _,_ => None
  end
| GenNode 2 [gt1; gt2] =>
  match gt2S gt1, gt2S gt2 with
  | Some S1, Some S2 => Some (S_assume S1 S2)
  | _,_ => None
  end
| GenNode 3 [gt1; gt2] =>
  match gt2S gt1, gt2S gt2 with
  | Some S1, Some S2 => Some (S_par S1 S2)
  | _,_ => None
  end
| GenNode 4 [GenLeaf (inr V0)] => Some (S_var V0)
| _ => None
end.

Fixpoint P2gt (P0 : P) : gen_tree (c + S + string) :=
match P0 with
| P_implements c1 S1 =>
    GenNode 0 [GenLeaf (inl (inl c1)); GenLeaf (inl (inr S1))]
| P_refines S1 S2 =>
    GenNode 1 [GenLeaf (inl (inr S1)); GenLeaf (inl (inr S2))]
| P_asserts S1 =>
    GenNode 2 [GenLeaf (inl (inr S1))]
| P_forall_c q1 P1 =>
    GenNode 3 [GenLeaf (inr q1); P2gt P1]
| P_exists_c q1 P1 =>
    GenNode 4 [GenLeaf (inr q1); P2gt P1]
| P_forall_S V1 P1 =>
    GenNode 5 [GenLeaf (inr V1); P2gt P1]
| P_exists_S V1 P1 =>
    GenNode 6 [GenLeaf (inr V1); P2gt P1]
| P_implies P1 P2 =>
    GenNode 7 [P2gt P1; P2gt P2]
| P_and P1 P2 =>
    GenNode 8 [P2gt P1; P2gt P2]
| P_or P1 P2 =>
    GenNode 9 [P2gt P1; P2gt P2]
| P_not P1 =>
    GenNode 10 [P2gt P1]
| P_c_eq c1 c2 =>
    GenNode 11 [GenLeaf (inl (inl c1)); GenLeaf (inl (inl c2))]
| P_S_eq S1 S2 =>
    GenNode 12 [GenLeaf (inl (inr S1)); GenLeaf (inl (inr S2))]
end.

Fixpoint gt2P (gt : gen_tree (c + S + string)) : option P :=
match gt with
| GenNode 0 [GenLeaf (inl (inl c1)); GenLeaf (inl (inr S1))] =>
    Some (P_implements c1 S1)
| GenNode 1 [GenLeaf (inl (inr S1)); GenLeaf (inl (inr S2))] =>
    Some (P_refines S1 S2)
| GenNode 2 [GenLeaf (inl (inr S1))] =>
    Some (P_asserts S1)
| GenNode 3 [GenLeaf (inr q1); gt] =>
    match gt2P gt with
    | Some P1 => Some (P_forall_c q1 P1)
    | None => None
    end
| GenNode 4 [GenLeaf (inr q1); gt] =>
    match gt2P gt with
    | Some P1 => Some (P_exists_c q1 P1)
    | None => None
    end
| GenNode 5 [GenLeaf (inr V1); gt] =>
    match gt2P gt with
    | Some P1 => Some (P_forall_S V1 P1)
    | None => None
    end
| GenNode 6 [GenLeaf (inr V1); gt] =>
    match gt2P gt with
    | Some P1 => Some (P_exists_S V1 P1)
    | None => None
    end
| GenNode 7 [gt1; gt2] =>
    match gt2P gt1, gt2P gt2 with
    | Some P1, Some P2 => Some (P_implies P1 P2)
    | _,_ => None
    end
| GenNode 8 [gt1; gt2] =>
    match gt2P gt1, gt2P gt2 with
    | Some P1, Some P2 => Some (P_and P1 P2)
    | _,_ => None
    end
| GenNode 9 [gt1; gt2] =>
    match gt2P gt1, gt2P gt2 with
    | Some P1, Some P2 => Some (P_or P1 P2)
    | _,_ => None
    end
| GenNode 10 [gt] =>
    match gt2P gt with
    | Some P1 => Some (P_not P1)
    | None => None
    end
| GenNode 11 [GenLeaf (inl (inl c1)); GenLeaf (inl (inl c2))] =>
    Some (P_c_eq c1 c2)
| GenNode 12 [GenLeaf (inl (inr S1)); GenLeaf (inl (inr S2))] =>
    Some (P_S_eq S1 S2)
| _ => None
end.

#[export] Instance Sc_eq_dec : EqDecision Sc.
Proof. by intros x y; solve_decision. Defined.

#[export] Instance c_eq_dec : EqDecision c.
Proof. by intros x y; solve_decision. Defined.

#[export] Instance S_eq_dec : EqDecision S.
Proof. by intros x y; solve_decision. Defined.

#[export] Instance P_eq_dec : EqDecision P.
Proof. intros x y; solve_decision. Defined.

#[export] Instance Sc_countable : Countable Sc.
Proof.
by apply (inj_countable Sc2gt gt2Sc); destruct x.
Defined.

#[export] Instance c_countable : Countable c.
Proof.
apply (inj_countable c2gt gt2c).
by induction x; cbn; try done; rewrite IHx1, IHx2.
Defined.

#[export] Instance S_countable : Countable S.
Proof.
apply (inj_countable S2gt gt2S).
by induction x; cbn; try done; rewrite IHx1, IHx2.
Defined.

#[export] Instance P_countable : Countable P.
Proof. 
apply (inj_countable P2gt gt2P).
by induction x; cbn; try done; try rewrite ?IHx, ?IHx1, ?IHx2.
Defined.

Definition SVARIANT (s:stringset) : string :=
 fresh_string_of_set "" s.

Fixpoint fv_c (c0 : c) : stringset :=
match c0 with
| c_const _ => ∅
| c_comp c1 c2 => fv_c c1 ∪ fv_c c2
| c_var x => {[ x ]}
end.

Fixpoint fv_S (S0 : S) : stringset :=
match S0 with
| S_const _ => ∅
| S_conj S1 S2 => fv_S S1 ∪ fv_S S2
| S_assume S1 S2 => fv_S S1 ∪ fv_S S2
| S_par S1 S2 => fv_S S1 ∪ fv_S S2
| S_var x => {[ x ]}
end.

Fixpoint fv_P_c (P0 : P) : stringset :=
match P0 with
| P_implements c1 _ => fv_c c1
| P_refines S1 S2 => ∅
| P_asserts S1 => ∅
| P_forall_c x P1 => fv_P_c P1 ∖ {[ x ]}
| P_forall_S x P1 => fv_P_c P1
| P_exists_c x P1 => fv_P_c P1 ∖ {[ x ]}
| P_exists_S x P1 => fv_P_c P1
| P_implies P1 P2 => fv_P_c P1 ∪ fv_P_c P2
| P_and P1 P2 => fv_P_c P1 ∪ fv_P_c P2
| P_or P1 P2 => fv_P_c P1 ∪ fv_P_c P2
| P_not P1 => fv_P_c P1
| P_c_eq c1 c2 => fv_c c1 ∪ fv_c c2
| P_S_eq S1 S2 => ∅
end.

Fixpoint fv_P_S (P0 : P) : stringset :=
match P0 with
| P_implements _ S1 => fv_S S1
| P_refines S1 S2 => fv_S S1 ∪ fv_S S2
| P_asserts S1 => fv_S S1
| P_forall_c x P1 => fv_P_S P1
| P_forall_S x P1 => fv_P_S P1 ∖ {[ x ]}
| P_exists_c x P1 => fv_P_S P1
| P_exists_S x P1 => fv_P_S P1 ∖ {[ x ]}
| P_implies P1 P2 => fv_P_S P1 ∪ fv_P_S P2
| P_and P1 P2 => fv_P_S P1 ∪ fv_P_S P2
| P_or P1 P2 => fv_P_S P1 ∪ fv_P_S P2
| P_not P1 => fv_P_S P1
| P_c_eq c1 c2 => ∅
| P_S_eq S1 S2 => fv_S S1 ∪ fv_S S2
end.

Fixpoint csubst_c Mq (c0:c) : c :=
match c0 with
| c_const cn => c_const cn
| c_comp c1 c2 => c_comp (csubst_c Mq c1) (csubst_c Mq c2)
| c_var x => Mq x
end.

Fixpoint Ssubst_S MV (S0:S) : S :=
match S0 with
| S_const Sn => S_const Sn
| S_conj S1 S2 => S_conj (Ssubst_S MV S1) (Ssubst_S MV S2)
| S_assume S1 S2 => S_assume (Ssubst_S MV S1) (Ssubst_S MV S2)
| S_par S1 S2 => S_par (Ssubst_S MV S1) (Ssubst_S MV S2)
| S_var x => MV x
end.

Fixpoint csubst_P Mq (P0:P) : P :=
match P0 with
| P_implements c1 S1 => P_implements (csubst_c Mq c1) S1
| P_refines S1 S2 => P_refines S1 S2
| P_asserts S1 => P_asserts S1
| P_forall_c x P1 =>
    let Mq' := <[x := c_var x]>Mq in
    let z :=
      if decide (exists y, y ∈ fv_P_c (P_forall_c x P1) /\ x ∈ fv_c (Mq' y))
      then SVARIANT (fv_P_c (csubst_P Mq' P1)) else x in
    P_forall_c z (csubst_P (<[x := c_var z]>Mq) P1)
| P_forall_S x P1 => P_forall_S x (csubst_P Mq P1)
| P_exists_c x P1 =>
    let Mq' := <[x := c_var x]>Mq in
    let z :=
      if decide (exists y, y ∈ fv_P_c (P_exists_c x P1) /\ x ∈ fv_c (Mq' y))
      then SVARIANT (fv_P_c (csubst_P Mq' P1)) else x in
    P_exists_c z (csubst_P (<[x := c_var z]>Mq) P1)
| P_exists_S x P1 => P_exists_S x (csubst_P Mq P1)
| P_implies P1 P2 => P_implies (csubst_P Mq P1) (csubst_P Mq P2)
| P_and P1 P2 => P_and (csubst_P Mq P1) (csubst_P Mq P2)
| P_or P1 P2 => P_or (csubst_P Mq P1) (csubst_P Mq P2)
| P_not P1 => P_not (csubst_P Mq P1)
| P_c_eq c1 c2 => P_c_eq (csubst_c Mq c1) (csubst_c Mq c2)
| P_S_eq S1 S2 => P_S_eq S1 S2
end.

Fixpoint Ssubst_P MV (P0:P) : P :=
match P0 with
| P_implements c1 S1 => P_implements c1 (Ssubst_S MV S1)
| P_refines S1 S2 => P_refines (Ssubst_S MV S1) (Ssubst_S MV S2)
| P_asserts S1 => P_asserts (Ssubst_S MV S1)
| P_forall_c x P1 => P_forall_c x (Ssubst_P MV P1)
| P_forall_S x P1 =>
    let MV' := <[x := S_var x]>MV in
    let z :=
      if decide (exists y, y ∈ fv_P_S (P_forall_S x P1) /\ x ∈ fv_S (MV' y))
      then SVARIANT (fv_P_S (Ssubst_P MV' P1)) else x in
    P_exists_S z (Ssubst_P (<[x := S_var z]>MV) P1)
| P_exists_c x P1 => P_exists_c x (Ssubst_P MV P1)
| P_exists_S x P1 =>
    let MV' := <[x := S_var x]>MV in
    let z :=
      if decide (exists y, y ∈ fv_P_S (P_exists_S x P1) /\ x ∈ fv_S (MV' y))
      then SVARIANT (fv_P_S (Ssubst_P MV' P1)) else x in
    P_exists_S z (Ssubst_P (<[x := S_var z]>MV) P1)
| P_implies P1 P2 => P_implies (Ssubst_P MV P1) (Ssubst_P MV P2)
| P_and P1 P2 => P_and (Ssubst_P MV P1) (Ssubst_P MV P2)
| P_or P1 P2 => P_or (Ssubst_P MV P1) (Ssubst_P MV P2)
| P_not P1 => P_not (Ssubst_P MV P1)
| P_c_eq c1 c2 => P_c_eq c1 c2
| P_S_eq S1 S2 => P_S_eq (Ssubst_S MV S1) (Ssubst_S MV S2)
end.


Definition G : Set := (gset P).
(* definitions *)

(* defns spec_proof *)
Inductive spec_holds : G -> P -> Prop :=    (* defn spec_holds *)
 | ax : forall (G5:G) (P5:P),
     spec_holds  ({[  P5  ]} ∪  G5 )  P5
 | ref_in : forall (G5:G) (S1 S2:S) (q5:q),
     spec_holds G5 (P_forall_c q5 (P_implies (P_implements (c_var q5) S1) (P_implements (c_var q5) S2))) ->
     spec_holds G5 (P_refines S1 S2)
 | ref_el : forall (G5:G) (c5:c) (S2 S1:S),
     spec_holds G5 (P_implements c5 S1) ->
     spec_holds G5 (P_refines S1 S2) ->
     spec_holds G5 (P_implements c5 S2)
 | assn_in : forall (G5:G) (S5:S) (q1 q2:q),
      ( q1  <>  q2 )  ->
     spec_holds G5 (P_forall_c q1 (P_forall_c q2 (P_implies (P_implements (c_var q1) S5) (P_implements (c_comp (c_var q1) (c_var q2)) S5)))) ->
     spec_holds G5 (P_asserts S5)
 | assn_el : forall (G5:G) (c1 c2:c) (S5:S),
     spec_holds G5 (P_asserts S5) ->
     spec_holds G5 (P_implements c1 S5) ->
     spec_holds G5 (P_implements (c_comp c1 c2) S5)
 | conj_in : forall (G5:G) (c5:c) (S1 S2:S),
     spec_holds G5 (P_implements c5 S1) ->
     spec_holds G5 (P_implements c5 S2) ->
     spec_holds G5 (P_implements c5 (S_conj S1 S2))
 | conj_el1 : forall (G5:G) (c5:c) (S1 S2:S),
     spec_holds G5 (P_implements c5 (S_conj S1 S2)) ->
     spec_holds G5 (P_implements c5 S1)
 | conj_el2 : forall (G5:G) (c5:c) (S2 S1:S),
     spec_holds G5 (P_implements c5 (S_conj S1 S2)) ->
     spec_holds G5 (P_implements c5 S2)
 | par_in : forall (G5:G) (c1 c2:c) (S1 S2:S),
     spec_holds G5 (P_implements c1 S1) ->
     spec_holds G5 (P_implements c2 S2) ->
     spec_holds G5 (P_implements (c_comp c1 c2) (S_par S1 S2))
 | par_el : forall (G5:G) (q1 q2:q) (S1 S2:S) (c5:c),
      ( q1  <>  q2 )  ->
      ( q1  ∉   (fv_c  c5 )  )  ->
      ( q2  ∉   (fv_c  c5 )  )  ->
     spec_holds G5 (P_implements c5 (S_par S1 S2)) ->
     spec_holds G5 (P_exists_c q1 (P_exists_c q2 (P_and (P_implements (c_var q1) S1) (P_and (P_implements (c_var q2) S2) (P_c_eq c5 (c_comp (c_var q1) (c_var q2)))))))
 | cont_in : forall (G5:G) (c5:c) (S1 S2:S) (q5:q),
      ( q5  ∉   (fv_c  c5 )  )  ->
     spec_holds G5 (P_forall_c q5 (P_implies (P_implements (c_var q5) S1) (P_implements (c_comp (c_var q5) c5) S2))) ->
     spec_holds G5 (P_implements c5 (S_assume S1 S2))
 | cont_el : forall (G5:G) (c1 c2:c) (S2 S1:S),
     spec_holds G5 (P_implements c1 S1) ->
     spec_holds G5 (P_implements c2 (S_assume S1 S2)) ->
     spec_holds G5 (P_implements (c_comp c1 c2) S2)
 | cre : forall (G5:G) (c5:c) (S2 S3 S1:S),
     spec_holds G5 (P_implements c5 (S_conj S1 S2)) ->
     spec_holds G5 (P_refines S2 S3) ->
     spec_holds G5 (P_implements c5 (S_conj S2 S3))
 | cr : forall (G5:G) (c5:c) (S2 S3 S1:S),
     spec_holds G5 (P_implements c5 (S_conj S1 S3)) ->
     spec_holds G5 (P_refines S1 S2) ->
     spec_holds G5 (P_implements c5 (S_conj S2 S3))
 | and_in : forall (G5:G) (P1 P2:P),
     spec_holds G5 P1 ->
     spec_holds G5 P2 ->
     spec_holds G5 (P_and P1 P2)
 | and_el1 : forall (G5:G) (P1 P2:P),
     spec_holds G5 (P_and P1 P2) ->
     spec_holds G5 P1
 | and_el2 : forall (G5:G) (P2 P1:P),
     spec_holds G5 (P_and P1 P2) ->
     spec_holds G5 P2
 | imp_in : forall (G5:G) (P1 P2:P),
     spec_holds  ({[  P1  ]} ∪  G5 )  P2 ->
     spec_holds G5 (P_implies P1 P2)
 | imp_el : forall (G5:G) (P2 P1:P),
     spec_holds G5 (P_implies P1 P2) ->
     spec_holds G5 P1 ->
     spec_holds G5 P2
 | or_in1 : forall (G5:G) (P1 P2:P),
     spec_holds G5 P1 ->
     spec_holds G5 (P_or P1 P2)
 | or_in2 : forall (G5:G) (P1 P2:P),
     spec_holds G5 P2 ->
     spec_holds G5 (P_or P1 P2)
 | or_el : forall (G5:G) (P_5 P1 P2:P),
     spec_holds G5 (P_or P1 P2) ->
     spec_holds  ({[  P1  ]} ∪  G5 )  P_5 ->
     spec_holds  ({[  P2  ]} ∪  G5 )  P_5 ->
     spec_holds G5 P_5
 | not_in : forall (G5:G) (P1 P2:P),
     spec_holds  ({[  P1  ]} ∪  G5 )  P2 ->
     spec_holds  ({[  P1  ]} ∪  G5 )  (P_not P2) ->
     spec_holds G5 (P_not P1)
 | not_el : forall (G5:G) (P5:P),
     spec_holds G5 (P_not (P_not P5)) ->
     spec_holds G5 P5
 | all_el_c : forall (G5:G) (P5:P) (c5:c) (q5:q),
     spec_holds G5 (P_forall_c q5 P5) ->
     spec_holds G5  (csubst_P (<[  q5 := c5  ]>c_var)  P5 ) 
 | all_in_c : forall (G5:G) (q5:q) (P5:P) (q':q),
      ( q'  ∉   (  (fv_P_c  P5 )   ∪   (⋃ (map fv_P_c (elements  G5 )))  )  )  ->
     spec_holds G5  (csubst_P (<[  q5 := (c_var q')  ]>c_var)  P5 )  ->
     spec_holds G5 (P_forall_c q5 P5)
 | eq_el_c : forall (G5:G) (P5:P) (c':c) (q5:q) (c5:c),
     spec_holds G5 (P_c_eq c5 c') ->
     spec_holds G5  (csubst_P (<[  q5 := c5  ]>c_var)  P5 )  ->
     spec_holds G5  (csubst_P (<[  q5 := c'  ]>c_var)  P5 ) 
 | all_el_S : forall (G5:G) (P5:P) (S5:S) (V5:V),
     spec_holds G5 (P_forall_S V5 P5) ->
     spec_holds G5  (Ssubst_P (<[  V5 := S5  ]>S_var)  P5 ) 
 | all_in_S : forall (G5:G) (V5:V) (P5:P) (V':V),
      ( V'  ∉   (  (fv_P_S  P5 )   ∪   (⋃ (map fv_P_S (elements  G5 )))  )  )  ->
     spec_holds G5  (Ssubst_P (<[  V5 := (S_var V')  ]>S_var)  P5 )  ->
     spec_holds G5 (P_forall_S V5 P5)
 | eq_el_S : forall (G5:G) (P5:P) (S':S) (V5:V) (S5:S),
     spec_holds G5 (P_S_eq S5 S') ->
     spec_holds G5  (Ssubst_P (<[  V5 := S5  ]>S_var)  P5 )  ->
     spec_holds G5  (Ssubst_P (<[  V5 := S'  ]>S_var)  P5 ) 
 | ex_in_c : forall (G5:G) (q5:q) (P5:P) (c5:c),
     spec_holds G5  (csubst_P (<[  q5 := c5  ]>c_var)  P5 )  ->
     spec_holds G5 (P_exists_c q5 P5)
 | ex_el_c : forall (G5 G':G) (P':P) (q':q) (P5:P) (q5:q),
      ( q'  ∉   (  (fv_P_c  P5 )   ∪   (fv_P_c  P' )  )  )  ->
      ( q'  ∉   (  (⋃ (map fv_P_c (elements  G5 )))   ∪   (⋃ (map fv_P_c (elements  G' )))  )  )  ->
     spec_holds G5 (P_exists_c q5 P5) ->
     spec_holds  ({[   (csubst_P (<[  q5 := (c_var q')  ]>c_var)  P5 )   ]} ∪  G' )  P' ->
     spec_holds  ( G5  ∪  G' )  P'
 | ex_in_S : forall (G5:G) (V5:V) (P5:P) (S5:S),
     spec_holds G5  (Ssubst_P (<[  V5 := S5  ]>S_var)  P5 )  ->
     spec_holds G5 (P_exists_S V5 P5)
 | ex_el_S : forall (G5 G':G) (P':P) (V':V) (P5:P) (V5:V),
      ( V'  ∉   (  (fv_P_S  P5 )   ∪   (fv_P_S  P' )  )  )  ->
      ( V'  ∉   (  (⋃ (map fv_P_S (elements  G5 )))   ∪   (⋃ (map fv_P_S (elements  G' )))  )  )  ->
     spec_holds G5 (P_exists_S V5 P5) ->
     spec_holds  ({[   (Ssubst_P (<[  V5 := (S_var V')  ]>S_var)  P5 )   ]} ∪  G' )  P' ->
     spec_holds  ( G5  ∪  G' )  P'.


