(* generated by Ott 0.34 from: ../ott/small.ott *)

Require Import Arith.
Require Import Bool.
Require Import List.
Require Import Ott.ott_list_core.


From stdpp Require Import prelude strings gmap stringmap functions countable.

Definition cn : Set := string. (* component constant name *)
Definition Sn : Set := string. (* specification constant name *)

Inductive c : Set :=  (* component term *)
 | c_const (cn5:cn) (* constant *)
 | c_comp (c5:c) (c':c) (* composition *).

Inductive S : Set :=  (* specification term *)
 | S_const (Sn5:Sn) (* constant *)
 | S_conj (S5:S) (S':S) (* conjunction *)
 | S_assume (S5:S) (S':S) (* assume-guarantee *)
 | S_par (S5:S) (S':S) (* parallel *).

Inductive P : Set :=  (* predicate *)
 | P_implements (c5:c) (S5:S) (* implements *)
 | P_refines (S5:S) (S':S) (* refines *)
 | P_implies (P5:P) (P':P) (* implies *)
 | P_and (P5:P) (P':P) (* conjunction *)
 | P_or (P5:P) (P':P) (* disjunction *)
 | P_not (P5:P) (* negation *).
Fixpoint c2gt (c0:c) : gen_tree string :=
match c0 with
| c_const cn0 => GenNode 0 [GenLeaf cn0]
| c_comp c1 c2 => GenNode 1 [c2gt c1; c2gt c2]
end.

Fixpoint gt2c (gt : gen_tree string) : option c :=
match gt with
| GenNode 0 [GenLeaf cn0] => Some (c_const cn0)
| GenNode 1 [gt1; gt2] =>
  match gt2c gt1, gt2c gt2 with
  | Some c1, Some c2 => Some (c_comp c1 c2)
  | _,_ => None
  end
| _ => None
end.

Fixpoint S2gt (S0:S) : gen_tree string :=
match S0 with
| S_const Sc0 => GenNode 0 [GenLeaf Sc0]
| S_conj S1 S2 => GenNode 1 [S2gt S1; S2gt S2]
| S_assume S1 S2 => GenNode 2 [S2gt S1; S2gt S2]
| S_par S1 S2 => GenNode 3 [S2gt S1; S2gt S2]
end.

Fixpoint gt2S (gt : gen_tree string) : option S :=
match gt with
| GenNode 0 [GenLeaf Sc0] => Some (S_const Sc0)
| GenNode 1 [gt1; gt2] =>
  match gt2S gt1, gt2S gt2 with
  | Some S1, Some S2 => Some (S_conj S1 S2)
  | _,_ => None
  end
| GenNode 2 [gt1; gt2] =>
  match gt2S gt1, gt2S gt2 with
  | Some S1, Some S2 => Some (S_assume S1 S2)
  | _,_ => None
  end
| GenNode 3 [gt1; gt2] =>
  match gt2S gt1, gt2S gt2 with
  | Some S1, Some S2 => Some (S_par S1 S2)
  | _,_ => None
  end
| _ => None
end.

Fixpoint P2gt (P0 : P) : gen_tree (c + S) :=
match P0 with
| P_implements c1 S1 =>
    GenNode 0 [GenLeaf (inl c1); GenLeaf (inr S1)]
| P_refines S1 S2 =>
    GenNode 1 [GenLeaf (inr S1); GenLeaf (inr S2)]
| P_implies P1 P2 =>
    GenNode 2 [P2gt P1; P2gt P2]
| P_and P1 P2 =>
    GenNode 3 [P2gt P1; P2gt P2]
| P_or P1 P2 =>
    GenNode 4 [P2gt P1; P2gt P2]
| P_not P1 =>
    GenNode 5 [P2gt P1]
end.

Fixpoint gt2P (gt : gen_tree (c + S)) : option P :=
match gt with
| GenNode 0 [GenLeaf (inl c1); GenLeaf (inr S1)] =>
    Some (P_implements c1 S1)
| GenNode 1 [GenLeaf (inr S1); GenLeaf (inr S2)] =>
    Some (P_refines S1 S2)
| GenNode 2 [gt1; gt2] =>
    match gt2P gt1, gt2P gt2 with
    | Some P1, Some P2 => Some (P_implies P1 P2)
    | _,_ => None
    end
| GenNode 3 [gt1; gt2] =>
    match gt2P gt1, gt2P gt2 with
    | Some P1, Some P2 => Some (P_and P1 P2)
    | _,_ => None
    end
| GenNode 4 [gt1; gt2] =>
    match gt2P gt1, gt2P gt2 with
    | Some P1, Some P2 => Some (P_or P1 P2)
    | _,_ => None
    end
| GenNode 5 [gt] =>
    match gt2P gt with
    | Some P1 => Some (P_not P1)
    | None => None
    end
| _ => None
end.

#[export] Instance c_eq_dec : EqDecision c.
Proof. by intros x y; solve_decision. Defined.

#[export] Instance S_eq_dec : EqDecision S.
Proof. by intros x y; solve_decision. Defined.

#[export] Instance P_eq_dec : EqDecision P.
Proof. intros x y; solve_decision. Defined.

#[export] Instance c_countable : Countable c.
Proof.
apply (inj_countable c2gt gt2c).
by induction x; cbn; try done; rewrite IHx1, IHx2.
Defined.

#[export] Instance S_countable : Countable S.
Proof.
apply (inj_countable S2gt gt2S).
by induction x; cbn; try done; rewrite IHx1, IHx2.
Defined.

#[export] Instance P_countable : Countable P.
Proof. 
apply (inj_countable P2gt gt2P).
by induction x; cbn; try done; try rewrite ?IHx, ?IHx1, ?IHx2.
Defined.


Definition G : Set := (gset P).
(* definitions *)

(* defns spec_proof *)
Inductive spec_holds : G -> P -> Prop :=    (* defn spec_holds *)
 | ax : forall (G5:G) (P5:P),
     spec_holds  ({[  P5  ]} ∪  G5 )  P5
 | ref_el : forall (G5:G) (c5:c) (S2 S1:S),
     spec_holds G5 (P_implements c5 S1) ->
     spec_holds G5 (P_refines S1 S2) ->
     spec_holds G5 (P_implements c5 S2)
 | conj_in : forall (G5:G) (c5:c) (S1 S2:S),
     spec_holds G5 (P_implements c5 S1) ->
     spec_holds G5 (P_implements c5 S2) ->
     spec_holds G5 (P_implements c5 (S_conj S1 S2))
 | conj_el1 : forall (G5:G) (c5:c) (S1 S2:S),
     spec_holds G5 (P_implements c5 (S_conj S1 S2)) ->
     spec_holds G5 (P_implements c5 S1)
 | conj_el2 : forall (G5:G) (c5:c) (S2 S1:S),
     spec_holds G5 (P_implements c5 (S_conj S1 S2)) ->
     spec_holds G5 (P_implements c5 S2)
 | par_in : forall (G5:G) (c1 c2:c) (S1 S2:S),
     spec_holds G5 (P_implements c1 S1) ->
     spec_holds G5 (P_implements c2 S2) ->
     spec_holds G5 (P_implements (c_comp c1 c2) (S_par S1 S2))
 | cont_el : forall (G5:G) (c1 c2:c) (S2 S1:S),
     spec_holds G5 (P_implements c1 S1) ->
     spec_holds G5 (P_implements c2 (S_assume S1 S2)) ->
     spec_holds G5 (P_implements (c_comp c1 c2) S2)
 | cre : forall (G5:G) (c5:c) (S2 S3 S1:S),
     spec_holds G5 (P_implements c5 (S_conj S1 S2)) ->
     spec_holds G5 (P_refines S2 S3) ->
     spec_holds G5 (P_implements c5 (S_conj S2 S3))
 | cr : forall (G5:G) (c5:c) (S2 S3 S1:S),
     spec_holds G5 (P_implements c5 (S_conj S1 S3)) ->
     spec_holds G5 (P_refines S1 S2) ->
     spec_holds G5 (P_implements c5 (S_conj S2 S3))
 | and_in : forall (G5:G) (P1 P2:P),
     spec_holds G5 P1 ->
     spec_holds G5 P2 ->
     spec_holds G5 (P_and P1 P2)
 | and_el1 : forall (G5:G) (P1 P2:P),
     spec_holds G5 (P_and P1 P2) ->
     spec_holds G5 P1
 | and_el2 : forall (G5:G) (P2 P1:P),
     spec_holds G5 (P_and P1 P2) ->
     spec_holds G5 P2
 | imp_in : forall (G5:G) (P1 P2:P),
     spec_holds  ({[  P1  ]} ∪  G5 )  P2 ->
     spec_holds G5 (P_implies P1 P2)
 | imp_el : forall (G5:G) (P2 P1:P),
     spec_holds G5 (P_implies P1 P2) ->
     spec_holds G5 P1 ->
     spec_holds G5 P2
 | or_in1 : forall (G5:G) (P1 P2:P),
     spec_holds G5 P1 ->
     spec_holds G5 (P_or P1 P2)
 | or_in2 : forall (G5:G) (P1 P2:P),
     spec_holds G5 P2 ->
     spec_holds G5 (P_or P1 P2)
 | or_el : forall (G5:G) (P_5 P1 P2:P),
     spec_holds G5 (P_or P1 P2) ->
     spec_holds  ({[  P1  ]} ∪  G5 )  P_5 ->
     spec_holds  ({[  P2  ]} ∪  G5 )  P_5 ->
     spec_holds G5 P_5
 | not_in : forall (G5:G) (P1 P2:P),
     spec_holds  ({[  P1  ]} ∪  G5 )  P2 ->
     spec_holds  ({[  P1  ]} ∪  G5 )  (P_not P2) ->
     spec_holds G5 (P_not P1)
 | not_el : forall (G5:G) (P5:P),
     spec_holds G5 (P_not (P_not P5)) ->
     spec_holds G5 P5.


